#! /usr/bin/env python
import os
import xarray as xr

if __name__ == '__main__':
    import argparse
    import sys
    p = argparse.ArgumentParser(description='Dump zarr file')
    p.add_argument('-v', help='Variable')
    p.add_argument('file_in', type=str, help='zarr file')
    args = p.parse_args()

    if not os.path.exists(args.file_in):
        print(f'zarrdump: cannot access {args.file_in}: no such file')
        sys.exit(1)

    with xr.open_zarr(args.file_in, decode_times=False, decode_coords=False) as ds:
        ds.info()
        if args.v is not None:
            print()
            for v in args.v.split(','):
                if v in ds:
                    print(f'{v} = {ds[v].values}\n')
                else:
                    raise ValueError(f'Variable {v} not found in {args.file_in}')
